#!/bin/bash

echo "Starting postBuild script..."

# Create the target directory if it doesn't exist
mkdir -p /home/jovyan/.jupyter/jupyter_ai

# Copy the config.json file to the target directory
cp .binder/config.json /home/jovyan/.jupyter/jupyter_ai/config.json

echo "postBuild script completed."
